### PR TITLE
Embed a commit date and hash

### PR DESCRIPTION
**Pull request by h-east**
in `b:loaded_syntax_vim_ex`

like this: (on Vim)

``` vim
:echo b:loaded_syntax_vim_ex
2016-04-16T11:57:44+09:00 48ae020
```

### CODE REVIEW

**Comment by h-east** [comment]
@koron Please review this.  If looks good then could merge this.

**Comment by koron** [comment]
I'll arrange this. Points are
- [x] the string should be rewritten in `make`
- [x] the string should be tested in `make test`
- [x] the string should be given/injected by .travis.yml

**Comment by koron** [comment]
fixed by #12

**Comment by h-east** [comment]
Thanks:+1:

**Pull request merged**
