### PR TITLE
Add support for Lua embedded in Neovim

### PR DESCRIPTION
**Pull request by Iron-E**
This is the same as #18 but the changes are to the generator branch.

### CODE REVIEW

**Comment by Iron-E** [comment]
@k-takata are there any other steps to altering the generator? Should I run the script?

**Comment by k-takata** [comment]
No, LGTM.
But I leave this to @h-east.

**Comment by Iron-E** [comment]
Sounds good— just making sure.

**Comment by h-east** [comment]
This product is for only BMV([Bram maintained Vim](https://github.com/vim/vim)).
Neovim is not supported.
Because this product parses BMV's C source code and semi-automatically generates syntax/vim.vim.

As you know, BMV and Neovim support slightly different commands, functions and events etc...
It's difficult to support both.

Closing this.
Thanks.

--
Best regards,
Hirohito Higashi (h_east)

**Comment by Iron-E** [comment]
Thanks for the detailed response. I understand where you're coming from— half of my own plugins _only_ support Neovim.

I guess the next step for me would be to maintain the fork. Thanks for all the help, guys!

**Pull request closed without merging**
